services:
  app:
    depends_on:
      - db
    environment:
      - DATABASE_TYPE=postgres
      - DATABASE_URL=postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-lorecard}

  db:
    image: postgres:13
    container_name: lorecard_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-lorecard}
    ports:
      - "5432:5432"
    volumes:
      - lorecard_postgres_data:/var/lib/postgresql/data

volumes:
  lorecard_postgres_data:
